### ISSUE TITLE
AoT compilation failed on nested lazy-loaded sub modules

### ISSUE THREAD

**Issue by showlong** [qdouble/angular-webpack2-starter#156] opened 2016-11-02 21:44 UTC
I use this lazy loading approach to my projects. Everything works fine with JiT but failed with AoT.
In this demo example, there is only one parent module to lazy load sub modules but I have parent module to lazy load sub modules and sub modules to lazy load sub-sub modules.
The code seems compiled fine until the final step to link and it failed to find the sub-sub modules with the relative path to module.

Do you have example to demo lazy load sub-sub modules with AoT?

**Comment by DzmitryShylovich** [comment] 2016-11-02 21:50
Paste your router config

**Comment by michalstepien** [comment] 2016-11-02 22:08
I have the same problem.

**Comment by showlong** [comment] 2016-11-02 22:15
Path: app/main/health/
Top Module routs:
export const routes: Routes = [
    { path: '', redirectTo: 'login', pathMatch: 'full'},
    { path: 'login', loadChildren: "./login/login.module#LoginModule" },
    {path: "content",
        canActivate: [MainRoutesGuard],
        loadChildren: "./main/main-content.module#MainContentModule" }
];

main content module routs:
const routes: Routes = [
    {path: '', component: MainContentComponent,
        resolve: {
            bootstrap: BootstrapResolver
        },
        children: [
            {path: '', redirectTo: 'dashboard', pathMatch: 'full'},
            {path: "dashboard", loadChildren: "./home/dashboard.module#DashboardModule" },
            {path: "alert", loadChildren: "./health/health-alerts.module#HealthAlertsModule" },
            {path: 'status', component: HealthCurAlertComponent},
            {path: "charts", loadChildren: "./charts/charts.module#ChartsModule" }
        ]
    }
];

Alert module routes:
const routes: Routes = [
    {path: '', component: HealthAlertsComponent,

        children: [
            {path: '', redirectTo: 'active', pathMatch: 'full'},
            {path: "active", loadChildren: "./health-current-alert.module#HealthCurrentAlertModule" },
            {path: "historic", loadChildren: "./health-historic-alert.module#HealthHistoricAlertModule" },

        ]
    }

];

AoT failed message:
ERROR in ./src/compiled/src/app/app.ddvso.module.ngfactory.ts
Module not found: Error: Can't resolve './health-current-alert.module.ngfactory' in '/Users/hot/AoT/ddvso/src/compiled/src/app'
 @ ./src/compiled/src/app/app.ddvso.module.ngfactory.ts 585:71-127
 @ ./src/main.browser.aot.ts

**Comment by qdouble** [comment] 2016-11-02 23:05
@showlong have you tested this on any other seed that uses aot? It's probably an angular bug.

**Comment by DzmitryShylovich** [comment] 2016-11-02 23:06
or router loader bug

**Comment by showlong** [comment] 2016-11-02 23:12
I did try other loader approach and failed with AoT at this step but worked with JiT.
So I was asking these demos sites to test the nested lazy loading case.
It could be an Angular bug.

**Comment by qdouble** [comment] 2016-11-03 01:27
@showlong yeah, I'll ask @brandonroberts  about it to see if it's a router-loader bug... but it seems like it's more likely just an angular bug, I'll keep this open until I hear from him and close it if it's just angular bug that you need file.

**Comment by brandonroberts** [comment] 2016-11-03 01:45
If you're trying to use the `angular2-router-loader` with the `AotPlugin` it won't work. The loader isn't for use alongside the plugin because the plugin handles lazy loading on its own. If you're doing AoT compilation using `ngc` then you're gonna have to reproduce the issue.

**Comment by qdouble** [comment] 2016-11-03 03:32
Will close since this seems to be an angular issue, but let me know if works elsewhere and I'll reopen, but I'd recommend filing a bug report on the angular repo.

**Closed by qdouble** 2016-11-03 03:32 UTC

**Comment by showlong** [comment] 2016-11-03 17:25
@brandonroberts I use the scripts from this starter, which use ngc to compile. The ngc compiled fine and all ngfactory code are generated on src/compiled directory. I used "compile" script and it failed with finding modules such as
ERROR in ./src/compiled/src/app/app.ddvso.module.ngfactory.ts
Module not found: Error: Can't resolve './health-current-alert.module.ngfactory' in '/Users/hot/AoT/ddvso/src/compiled/src/app'
@ ./src/compiled/src/app/app.ddvso.module.ngfactory.ts 585:71-127
@ ./src/main.browser.aot.ts

**I just want to know if others have the same issues or it is just my problem.**

**Comment by brandonroberts** [comment] 2016-11-07 01:51
@showlong I haven't seen others with the same issue. Is your `health-current-alert.module` in the `src/app` directory?

**Comment by showlong** [comment] 2016-11-07 02:07
It is under src/app/main/health directory. The three routes config above are located in three hierarchy directories:
src/app
src/app/main
src/app/main/health

All the "working" AoT starters or demo sites I found are just use one level of parent to children lazy loading, which does not fully test AoT with lazy loading. I personally think ngc does not correctly generate routes with hierarchy lazy loading structure.

**Comment by showlong** [comment] 2016-11-07 02:14
And my routes are work fine with JiT although I used to have issue with the default route of the sub lazy loading modules, which becomes the top default routes.  Somehow I feel AoT still has this bug.

**Comment by brandonroberts** [comment] 2016-11-07 02:15
@showlong it could be a bug with how AoT resolves the path to your lazy loaded submodule. What version of the plugin are you using? There has been a recent release that fixed some of the lazy loading issues.

**Comment by showlong** [comment] 2016-11-07 02:25
I use this angular-webpack2-starter with angular2.1.0  libraries. and I use compile script in the package.json file.
 If I use angular 2.2.0-rc0, the angular material does not work well although the JiT compiled fine.

**Comment by Luke265** [comment] 2016-12-20 22:00
I've submitted nested lazy loading PR in "angular-router-loader", it fixes this problem.
https://github.com/brandonroberts/angular-router-loader/pull/39

**Comment by Tuizi** [comment] 2017-01-08 23:42
I @Luke265 I ask to @brandonroberts to merge your fixe into the version 0.5.0, and @qdouble I made the PR #231 to fix this issue by updating this starter with this new version and apply changes. Thank you all
