### ISSUE TITLE
Angular Universal not working

### ISSUE THREAD

**Issue by meenie** [qdouble/angular-webpack2-starter#138] opened 2016-10-19 09:54 UTC
Using a fresh git clone and running `npm run universal`, when you load the the page, you get:
```
EXCEPTION: document is not defined
ORIGINAL STACKTRACE:
ReferenceError: document is not defined
    at new RippleRenderer (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/material/material.umd.js:193:31)
    at new MdRipple (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/material/material.umd.js:327:32)
    at AppView._View_MdButton1.createInternal (MdButton.ngfactory.js:63:24)
    at AppView.create (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:9178:25)
    at TemplateRef_.createEmbeddedView (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:7263:18)
    at ViewContainerRef_.createEmbeddedView (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:5103:39)
    at NgIf.Object.defineProperty.set [as ngIf] (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/common/bundles/common.umd.js:1632:41)
    at AppView._View_MdButton0.detectChangesInternal (MdButton.ngfactReferenceError: document is not defined
    at new RippleRenderer (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/material/material.umd.js:193:31)
    at new MdRipple (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/material/material.umd.js:327:32)
    at AppView._View_MdButton1.createInternal (MdButton.ngfactory.js:63:24)
    at AppView.create (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:9178:25)
    at TemplateRef_.createEmbeddedView (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:7263:18)
    at ViewContainerRef_.createEmbeddedView (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:5103:39)
    at NgIf.Object.defineProperty.set [as ngIf] (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/common/bundles/common.umd.js:1632:41)
    at AppView._View_MdButton0.detectChangesInternal (MdButton.ngfactory.js:42:25)
    at AppView.detectChanges (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:9325:18)
    at AppView.detectViewChildrenChanges (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:9351:23)
ory.js:42:25)
    at AppView.detectChanges (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:9325:18)
    at AppView.detectViewChildrenChanges (/Users/codyl/dev-files/angular-webpack2-starter/node_modules/@angular/core/bundles/core.umd.js:9351:23)
```

**Comment by qdouble** [comment] 2016-10-19 10:06
@meenie Material alpha-9 broke it's compatibility to Universal, but alpha 8 works fine, see this thread: https://github.com/qdouble/angular-webpack2-starter/issues/97

The Bootstrap and Universal Branch works without issue (https://github.com/qdouble/angular-webpack2-starter/tree/bootstrap-and-universal), so it's a material issue, not a Universal issue.

**Comment by meenie** [comment] 2016-10-19 10:13
Good to know! Suppose I should have looked at closed issues first :).  Thanks!

**Comment by meenie** [comment] 2016-10-19 10:22
So, I've tried the `bootstrap-and-universal` branch. Switched over, ran `npm install`, then `npm run universal` and the following errors happened:
```
    Hash: d4fbc14ee34793a1ac77
    Version: webpack 2.1.0-beta.25
    Time: 1741ms
    [./constants.js] ./constants.js 2.8 kB {0} [built]
    [./helpers.js] ./helpers.js 1.16 kB {0} [built]
    [./src/app/app.module.universal.node.ts] ./src/app/app.module.universal.node.ts 331 bytes {0} [built] [failed] [1 error]
    [./src/polyfills.server.ts] ./src/polyfills.server.ts 81 bytes {0} [built]
    [./src/rxjs.imports.ts] ./src/rxjs.imports.ts 891 bytes {0} [built]
    [./src/server.routes.ts] ./src/server.routes.ts 332 bytes {0} [built] [failed] [1 error]
    [./src/server.ts] ./src/server.ts 1.88 kB {0} [built]
        + 38 hidden modules

    ERROR in ./src/server.routes.ts
    Module parse failed: /Users/codyl/dev-files/angular-webpack2-starter/src/server.routes.ts Unexpected token (3:19)
    You may need an appropriate loader to handle this file type.
    | // Routes with html5pushstate
    | // ensure routes match client-side-app
    | export const routes: string[] = [
    |   'lazy',
    |   'sync'
     @ ./src/server.ts 19:0-41

    ERROR in ./src/app/app.module.universal.node.ts
    Module parse failed: /Users/codyl/dev-files/angular-webpack2-starter/src/app/app.module.universal.node.ts Unexpected character '@' (19:0)
    You may need an appropriate loader to handle this file type.
    | import { AppComponent } from './app.component';
    |
    | @NgModule({
    |   declarations: [
    |     AppComponent,
     @ ./src/server.ts 18:0-60

    ERROR in index.js from UglifyJs
    SyntaxError: Unexpected token punc «,», expected punc «:» [index.js:410,7]
```

**Comment by qdouble** [comment] 2016-10-19 10:25
can you try it from a fresh clone before I investigate? I know sometimes there can be issues caused by switching between branches
`git clone -b bootstrap-and-universal https://github.com/qdouble/angular-webpack2-starter.git`

**Comment by meenie** [comment] 2016-10-19 10:31
@qdouble: Using a fresh clone and it still happens.

**Comment by meenie** [comment] 2016-10-19 10:32
```
→ node -v                                                                                                               
v6.1.0

→ npm -v                                                                                                                
3.8.6

**Comment by qdouble** [comment] 2016-10-19 10:40
okay, I see it... must be something that popped up recently, will try to hunt it down

**Comment by qdouble** [comment] 2016-10-19 11:03
Should be fixed with this commit: https://github.com/qdouble/angular-webpack2-starter/commit/fd0208670b9fb05d30debeeecd1c09eb319afa0e 

Probably don't need that there, but seems to fail if I don't create any rules and broke when I removed what I set there from the material branch.

**Closed by qdouble** 2016-10-19 11:03 UTC

**Comment by vlados** [comment] 2018-12-09 00:22
This issue occur again.
Steps to reproduce:
1. clone
2. yarn
3. yarn run universal

### Result
```

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/vlado/code/udoma.bg/latest/dist/**/*
[nodemon] starting `node dist/server.js`
/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:3151
        __metadata("design:paramtypes", [Document, core_1.NgZone])
                                         ^

ReferenceError: Document is not defined
    at /Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:3151:42
    at Object.module.exports (/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:3154:2)
    at __webpack_require__ (/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:30:30)
    at Object.__decorate (/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:2927:20)
    at __webpack_require__ (/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:30:30)
    at Object.__decorate (/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:7028:27)
    at __webpack_require__ (/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:30:30)
    at module.exports (/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:73:18)
    at /Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:76:10
    at webpackUniversalModuleDefinition (/Users/vlado/code/udoma.bg/latest/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js:3:20)
[nodemon] app crashed - waiting for file changes before starting...
```
Node: v10.14.1
Yarn: 1.10.1
