### ISSUE TITLE
Angular material is not working on master branch (universal + material)

### ISSUE THREAD

**Issue by thecodr** [qdouble/angular-webpack2-starter#278] opened 2017-05-10 15:39 UTC
Angular material seems to be broken on the master branch. There are other issues mentioning about universal in production and is this still relevant today @qdouble ? We are thinking of using this template in production and angular material is our high priority.

**Comment by ShankarSumanth** [comment] 2017-05-10 22:38
I think this workaround should fix the issue. I have not tried this solution myself.

[@angular2/material/308](https://github.com/angular/material2/issues/308#issuecomment-275361791)

**Comment by qdouble** [comment] 2017-05-11 03:56
@thecodr material doesn't currently work with universal out of the box.... the hack in the link @ShankarSumanth  posted is for the previous version of Universal before they brought it into the core repo.

They say they will make material compatible with universal soon, so there's nothing I really need to do, it should simply work on a future update of material.  I suppose that will be after this is merged: https://github.com/angular/material2/pull/4251

**Comment by thecodr** [comment] 2017-05-12 12:19
@qdouble angular/material2#4251 is merged to master and I tested locally. Angular material is still not working in the template. I am trying to figure out the root cause but want to let you know.

**Comment by qdouble** [comment] 2017-05-12 16:09
@thecodr yeah, it appears they just haven't fully fixed material to work with universal yet...other than possibly using a different imports on the server than the browser, it shouldn't require much more than that if the problem is actually fixed on their end

**Comment by thecodr** [comment] 2017-05-12 18:01
@qdouble Is there anything we can do on our side ? I am happy to help. This is one of the best starter pack available in terms of angular universal and unfortunately, dependency on another package is spoiling the game :(

**Comment by qdouble** [comment] 2017-05-12 19:20
@thecodr The problem with trying to hack it, is every time there is an update to material or angular core, the hack may stop working as you'd be trying to manipulate private apis. I tried to do that early on, but gave up on that, because the project will just keep breaking or become non-upgradable and I don't see the point of using it in production if it's that unstable.

If you see a workable solution in a different project, I can see about implementing it in this project, but for now, I'll just wait for them to solve the problem.

**Comment by qdouble** [comment] 2017-05-12 23:51
@thecodr I just tested adding this from what I saw in the material repo thread: https://github.com/qdouble/angular-webpack2-starter/commit/8878c7525a55b2dd7b763a9467d88b0294d3e1d1

seems it will make material components at least render in universal... but it seems they'd have to do some additional updates to make it work fully without other patches

**Comment by thecodr** [comment] 2017-05-14 10:17
@qdouble I agree with you regarding the hacks. I pulled your changes and tested. It does look like Angular Material has to catch up a lot!!!!

**Comment by Alber70g** [comment] 2017-05-15 21:49
Hi, I just stumbled upon this awesome project. The only think is that material isn't working. Of course the issue is already surfaced, but is there any chance it'll be resolved in the near future? Or is there a quick-fix for this?

**Comment by qdouble** [comment] 2017-05-15 22:27
@Alber70g as far as something production ready, the Angular team says they will fix the compatibility issue "soon," so that can mean next week or several months from now. If you need to launch your project right away and have it use universal, you may want to consider using the bootstrap branch or just not using the material module. 

Me personally, I'm just delivering my project with Material using a normal AOT build and will just switch over to Universal as soon as it's compatible.

**Comment by Alber70g** [comment] 2017-05-15 23:32
@qdouble Thank you for your advice. I'm not in desperate need for Universal, but I figured it'd be nice to start with. I've already installed the non-universal branch, and that one looks fine.
There's only one thing that I stumbled upon. When I go to localhost:3000 the Logout to 192.xxx.xxx.xxx:3000/logout gives a CORS error. But when I go straight to that URL (192.xxx.xxx.xxx:3000) I get `Invalid Host header`.

**Comment by qdouble** [comment] 2017-05-15 23:39
@Alber70g if you  plan to use universal in the future, it would be better to just use the universal branch and just just run the regular build or compile command instead of the universal command. That way once the material issue is fixed, you'd just have to change build commands. 

The other issue is just because you're on the devServer, it should work fine on a normal server (or the prodserver).

**Comment by qdouble** [comment] 2017-05-15 23:45
@Alber70g in dev, you can use the reverse proxy option here if you need it to contact your actual api: https://github.com/qdouble/angular-webpack2-starter/blob/master/constants.js#L20

**Comment by Alber70g** [comment] 2017-05-16 10:08
I feel like I'm going off topic from the original issue here. But it seems that the /logout is an absolute URL instead of relative due to the inclusion of ${HOST} in http://${HOST}/logout. Shouldn't it be relative, or at least using the `location.hostname`?

**Comment by qdouble** [comment] 2017-05-16 10:17
@Alber70g it'd be dependent on your project, in my real project, the back office api is on a different port, so a relative URL wouldn't work... it's more so just an example, you can point it to where it should go for your actual project

**Comment by julienR2** [comment] 2017-05-17 09:45
Hi !
I'm using angular4 with serverside rendering and material2 together. They've improve quite a lot the compatibility, and I know run in few and few problems with it.
Few tricks are still needed to use it like:
* faking navigator and document on server side
webpack.server.config
```
module: {
    rules: [
      {
        test: /@angular(\\|\/)material/,
        loader: 'imports-loader',
        options: {
          window: '>global',
          'CSS': '>null',
          navigator: '>{get userAgent(){ return \'Chrome\'; }}',
          document: '>global.document'
        }
      }
    ]
  }
```
* NOOP the ObserveContent relying on MutationObserver only available on Browser
__workaround
```
import { ObserveContent } from '@angular/material';
ObserveContent.prototype.ngAfterContentInit = function () {}
```

I hope this help !

**Comment by qdouble** [comment] 2017-05-17 09:48
@julienR2 what file are you putting the ObserveContent stuff on?

**Comment by julienR2** [comment] 2017-05-17 09:50
Oups sorry was'nt that clear indeed.
I include the workaround in the main.server.ts

**Comment by qdouble** [comment] 2017-05-17 09:52
@julienR2 could you show how your version of that file?

**Comment by julienR2** [comment] 2017-05-17 10:00
Of course. However I have to specify I'm not using your repo, I landed on this issues looking for materials2 info, and though it could help.
But checking your repo it seems to be quite similar. (I used https://github.com/FrozenPandaz/ng-universal-demo/ to migrate to angular 4)

Anyway here is the main.server.ts
```
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import 'rxjs/Rx';
import './__workaround.server.ts'

import * as path from 'path';
import * as express from 'express';
import * as bodyParser from 'body-parser';
import * as cookieParser from 'cookie-parser';

import { enableProdMode } from '@angular/core';
import { platformServer, renderModuleFactory } from '@angular/platform-server';

import { ServerAppModule } from './app/server.module';
import { ngExpressEngine } from '@nguniversal/express-engine';
import { routes } from './server.routes';

if (process.env.NODE_ENV === 'production') {
  Raven.config(process.env.SENTRY_API_KEY).install();
}

enableProdMode();

const app = express();
const port = process.env.PORT || 3000;
const baseUrl = `http://0.0.0.0:${port}`;

app.engine('html', ngExpressEngine({
  bootstrap: ServerAppModule
}));

app.set('port', port);
app.set('view engine', 'html');
app.set('views', 'src');
app.set('json spaces', 2);

app.use(cookieParser());
app.use(bodyParser.json());

// Serve static files
app.use('/assets', express.static('src/assets', {maxAge: 30}));
app.use('/', express.static('dist', {index: false}));

function ngApp(req, res) {
  res.render('../dist/index', {
    req: req,
    res: res,
    cookies: req.cookies
  });
}

/**
 * use universal for specific routes
 */
routes.forEach(route => {
  app.get(`/${route.url}`, route.guard, ngApp);
  if (!route.index) {
    app.get(`/${route.url}/*`, route.guard, ngApp);
  }
});

app.listen(port, () => {
  console.log(`Listening at ${baseUrl}`);
});
```
with the workaround included linde 4 that only contained
``` 
import { ObserveContent } from '@angular/material';

ObserveContent.prototype.ngAfterContentInit = function () {}
```

**Comment by qdouble** [comment] 2017-05-17 10:23
@julienR2 thanks. yes, the projects are similar as far as the server implementation... with that patch, I notice that some material elements work just fine, but others give this message on the console:

```
ERROR { Error: Uncaught (in promise): TypeError: Cannot read property 'createElement' of undefined
TypeError: Cannot read property 'createElement' of undefined
```

do you experience that as well? And what version of material are you using?

**Comment by julienR2** [comment] 2017-05-17 10:36
I'm using the last version of material, 2.0.0-beta.5.
On which components do you experience this ? The last changes should have fixed most of these problems. (I only get on error using MdTabs for now)

**Comment by qdouble** [comment] 2017-05-17 11:03
@julienR2 I'm experiencing it even with MdInput. I just tested it out on the repo you're using and it gives the same results....(it shows the error in the server console, not the browser, so the input doesn't render until after the page is fully loaded).

I did the webpack patch here: https://github.com/qdouble/ng-universal-demo-material-test/blob/master/webpack/webpack.server.js
and the server patch here: https://github.com/qdouble/ng-universal-demo-material-test/blob/master/src/main.server.ts
and here:
https://github.com/qdouble/ng-universal-demo-material-test/blob/master/src/__workaround.server.ts

did I overlook anything or set something wrong?

**Comment by julienR2** [comment] 2017-05-17 11:11
Arg, I'm not using MdInput.. And Since they refactored it few release ago it probably use createElement now.. Still some trouble so..
Sorry for the noise and the time.. 
I'll add mdInput to the list of components needing a refactor (with mdTab) and open an issue on the subject.

**Comment by qdouble** [comment] 2017-05-17 11:18
@julienR2 np, thanks for looking into it, keep me updated if you encounter any more workarounds... 

hopefully the material team will start catching up on these compatibility issues soon

**Comment by julienR2** [comment] 2017-05-17 11:19
I will 👍 
Yeah I hope so too.. Fingers crossed.

**Comment by NickvdMeij** [comment] 2017-06-26 21:29
I'm currently using `@angular-material` version `2.0.0-beta.7` in combination with AOT and Universal and it works perfectly, no error with the production build or any AOT/JIT dev or production builds

**Comment by IAMtheIAM** [comment] 2017-09-22 20:56
Hey you should make a branch using [Materialize](http://materializecss.com) - its way better than angular material. Stable, easy to use, only jQuery dependency but thats easy with webpack ProvidePlugin.

**Comment by nhutcorp** [comment] 2017-09-23 02:24
By using pure Angular & Material Design on your project, you can create a performance app.
See this repo https://github.com/nhutcorp/angular-webpack2-starter

**Comment by qdouble** [comment] 2018-01-03 00:26
material and universal should work together fine now

**Closed by qdouble** 2018-01-03 00:26 UTC
